// Generated by using Rcpp::compileAttributes() -> do not edit by hand
// Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

#include "../inst/include/HsTrust.h"
#include "../inst/include/HsTrust_types.hpp"
#include <Rcpp.h>
#include <string>
#include <set>

using namespace Rcpp;

// get_init_tronC
SEXP get_init_tronC();
static SEXP _HsTrust_get_init_tronC_try() {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    rcpp_result_gen = Rcpp::wrap(get_init_tronC());
    return rcpp_result_gen;
END_RCPP_RETURN_ERROR
}
RcppExport SEXP _HsTrust_get_init_tronC() {
    SEXP rcpp_result_gen;
    {
        Rcpp::RNGScope rcpp_rngScope_gen;
        rcpp_result_gen = PROTECT(_HsTrust_get_init_tronC_try());
    }
    Rboolean rcpp_isInterrupt_gen = Rf_inherits(rcpp_result_gen, "interrupted-error");
    if (rcpp_isInterrupt_gen) {
        UNPROTECT(1);
        Rf_onintr();
    }
    Rboolean rcpp_isError_gen = Rf_inherits(rcpp_result_gen, "try-error");
    if (rcpp_isError_gen) {
        SEXP rcpp_msgSEXP_gen = Rf_asChar(rcpp_result_gen);
        UNPROTECT(1);
        Rf_error(CHAR(rcpp_msgSEXP_gen));
    }
    UNPROTECT(1);
    return rcpp_result_gen;
}
// get_tronC
SEXP get_tronC();
static SEXP _HsTrust_get_tronC_try() {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    rcpp_result_gen = Rcpp::wrap(get_tronC());
    return rcpp_result_gen;
END_RCPP_RETURN_ERROR
}
RcppExport SEXP _HsTrust_get_tronC() {
    SEXP rcpp_result_gen;
    {
        Rcpp::RNGScope rcpp_rngScope_gen;
        rcpp_result_gen = PROTECT(_HsTrust_get_tronC_try());
    }
    Rboolean rcpp_isInterrupt_gen = Rf_inherits(rcpp_result_gen, "interrupted-error");
    if (rcpp_isInterrupt_gen) {
        UNPROTECT(1);
        Rf_onintr();
    }
    Rboolean rcpp_isError_gen = Rf_inherits(rcpp_result_gen, "try-error");
    if (rcpp_isError_gen) {
        SEXP rcpp_msgSEXP_gen = Rf_asChar(rcpp_result_gen);
        UNPROTECT(1);
        Rf_error(CHAR(rcpp_msgSEXP_gen));
    }
    UNPROTECT(1);
    return rcpp_result_gen;
}
// test_tron_attributes
void test_tron_attributes();
RcppExport SEXP _HsTrust_test_tron_attributes() {
BEGIN_RCPP
    Rcpp::RNGScope rcpp_rngScope_gen;
    test_tron_attributes();
    return R_NilValue;
END_RCPP
}

// validate (ensure exported C++ functions exist before calling them)
static int _HsTrust_RcppExport_validate(const char* sig) { 
    static std::set<std::string> signatures;
    if (signatures.empty()) {
        signatures.insert("SEXP(*get_init_tronC)()");
        signatures.insert("SEXP(*get_tronC)()");
    }
    return signatures.find(sig) != signatures.end();
}

// registerCCallable (register entry points for exported C++ functions)
RcppExport SEXP _HsTrust_RcppExport_registerCCallable() { 
    R_RegisterCCallable("HsTrust", "_HsTrust_get_init_tronC", (DL_FUNC)_HsTrust_get_init_tronC_try);
    R_RegisterCCallable("HsTrust", "_HsTrust_get_tronC", (DL_FUNC)_HsTrust_get_tronC_try);
    R_RegisterCCallable("HsTrust", "_HsTrust_RcppExport_validate", (DL_FUNC)_HsTrust_RcppExport_validate);
    return R_NilValue;
}

RcppExport SEXP _rcpp_module_boot_HsTrust();

static const R_CallMethodDef CallEntries[] = {
    {"_HsTrust_get_init_tronC", (DL_FUNC) &_HsTrust_get_init_tronC, 0},
    {"_HsTrust_get_tronC", (DL_FUNC) &_HsTrust_get_tronC, 0},
    {"_HsTrust_test_tron_attributes", (DL_FUNC) &_HsTrust_test_tron_attributes, 0},
    {"_rcpp_module_boot_HsTrust", (DL_FUNC) &_rcpp_module_boot_HsTrust, 0},
    {"_HsTrust_RcppExport_registerCCallable", (DL_FUNC) &_HsTrust_RcppExport_registerCCallable, 0},
    {NULL, NULL, 0}
};

RcppExport void R_init_HsTrust(DllInfo *dll) {
    R_registerRoutines(dll, NULL, CallEntries, NULL, NULL);
    R_useDynamicSymbols(dll, FALSE);
}
